In [1]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['pdf.fonttype'] =42
import matplotlib.ticker as ticker
import matplotlib.patches as mpatches

In [2]:
df_colors = pd.read_csv("colors.csv")
df_colors.head()

   id            name     rgb is_trans
0  -1         Unknown  0033B2        f
1   0           Black  05131D        f
2   1            Blue  0055BF        f
3   2           Green  237841        f
4   3  Dark Turquoise  008F9B        f

In [3]:
df_parts = pd.read_csv("parts.csv")
df_parts.head()

  part_num                                               name  part_cat_id
0   0687b1                        Set 0687 Activity Booklet 1           17
1     0901  Baseplate 16 x 30 with Set 080 Yellow House Print            1
2     0902  Baseplate 16 x 24 with Set 080 Small White Hou...            1
3     0903     Baseplate 16 x 24 with Set 080 Red House Print            1
4     0904  Baseplate 16 x 24 with Set 080 Large White Hou...            1

In [4]:
df_partcat = pd.read_csv("part_categories.csv")
df_partcat.head()

   id                     name
0   1               Baseplates
1   2           Bricks Printed
2   3            Bricks Sloped
3   4  Duplo, Quatro and Primo
4   5           Bricks Special

In [5]:
df_sets = pd.read_csv("sets.csv")
df_sets.head()

  set_num                        name  year  theme_id  num_parts
0    00-1             Weetabix Castle  1970       414        471
1  0011-2           Town Mini-Figures  1978        84         12
2  0011-3  Castle 2 for 1 Bonus Offer  1987       199          2
3  0012-1          Space Mini-Figures  1979       143         12
4  0013-1          Space Mini-Figures  1979       143         12

In [6]:
df_themes = pd.read_csv("themes.csv")
df_themes.head()

   id            name  parent_id
0   1         Technic        NaN
1   2  Arctic Technic        1.0
2   3     Competition        1.0
3   4  Expert Builder        1.0
4   5           Model        1.0

In [7]:
df_inv = pd.read_csv("inventories.csv")
df_inv.head()

   id  version set_num
0   1        1  7922-1
1   3        1  3931-1
2   4        1  6942-1
3  15        1  5158-1
4  16        1   903-1

In [8]:
df_invparts = pd.read_csv("inventory_parts.csv")
df_invparts.head()

   inventory_id     part_num  color_id  quantity is_spare
0             1     48379c01        72         1        f
1             1        48395         7         1        f
2             1     mcsport6        25         1        f
3             1       paddle         0         1        f
4             3  11816pr0005        78         1        f

In [9]:
df_invsets = pd.read_csv("inventory_sets.csv")
df_invsets.head()

   inventory_id  set_num  quantity
0            35  75911-1         1
1            35  75912-1         1
2            39  75048-1         1
3            39  75053-1         1
4            50   4515-1         1

## Colors introduced every year

In [10]:
df_par_color = df_invparts.merge(df_colors, left_on='color_id', right_on='id', how='outer')

In [11]:
df_par_color

,inventory_id,part_num,color_id,quantity,is_spare,id,name,rgb,is_trans
0,1.0,48379c01,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
1,22.0,15573,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
2,22.0,2654,72.0,4.0,f,72,Dark Bluish Gray,6C6E68,f
3,22.0,3070b,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
4,22.0,3070b,72.0,1.0,t,72,Dark Bluish Gray,6C6E68,f
5,22.0,3666,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
6,22.0,4081b,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
7,22.0,41769,72.0,4.0,f,72,Dark Bluish Gray,6C6E68,f
8,22.0,41770,72.0,4.0,f,72,Dark Bluish Gray,6C6E68,f
9,22.0,43719,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
10,22.0,85984,72.0,3.0,f,72,Dark Bluish Gray,6C6E68,f
11,28.0,2431,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
12,28.0,2460,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
13,28.0,2569,72.0,1.0,t,72,Dark Bluish Gray,6C6E68,f
14,28.0,2569,72.0,2.0,f,72,Dark Bluish Gray,6C6E68,f
15,28.0,30162,72.0,3.0,f,72,Dark Bluish Gray,6C6E68,f
16,28.0,3020,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
17,28.0,3023,72.0,2.0,f,72,Dark Bluish Gray,6C6E68,f
18,28.0,30361c,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
19,28.0,30592,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
20,28.0,4162,72.0,2.0,f,72,Dark Bluish Gray,6C6E68,f
21,28.0,54101,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
22,28.0,6553,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
23,28.0,970c00,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
24,30.0,3937,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
25,32.0,3004,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
26,32.0,3660,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
27,37.0,32002,72.0,1.0,t,72,Dark Bluish Gray,6C6E68,f
28,37.0,32002,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
29,37.0,32199,72.0,1.0,f,72,Dark Bluish Gray,6C6E68,f
...,...,...,...,...,...,...,...,...,...
580225,14512.0,kraata3,183.0,1.0,f,183,Pearl White,F2F3F2,f
580226,14512.0,kraata4,183.0,1.0,f,183,Pearl White,F2F3F2,f
580227,14512.0,kraata5,183.0,1.0,f,183,Pearl White,F2F3F2,f
580228,14512.0,kraata6,183.0,1.0,f,183,Pearl White,F2F3F2,f
580229,15111.0,44138,183.0,2.0,f,183,Pearl White,F2F3F2,f
580230,15111.0,44140,183.0,1.0,f,183,Pearl White,F2F3F2,f
580231,15111.0,44807,183.0,1.0,f,183,Pearl White,F2F3F2,f
580232,15200.0,44138,183.0,2.0,f,183,Pearl White,F2F3F2,f
580233,15200.0,44140,183.0,1.0,f,183,Pearl White,F2F3F2,f
580234,15200.0,44807,183.0,1.0,f,183,Pearl White,F2F3F2,f
580235,8962.0,89917,133.0,1.0,f,133,Speckle Black-Gold,000000,f
580236,11058.0,89917,133.0,1.0,f,133,Speckle Black-Gold,000000,f
580237,11058.0,89918,133.0,1.0,f,133,Speckle Black-Gold,000000,f
580238,12521.0,89918,133.0,1.0,f,133,Speckle Black-Gold,000000,f
580239,15876.0,89917,133.0,1.0,f,133,Speckle Black-Gold,000000,f
580240,9555.0,30385,62.0,1.0,f,62,Chrome Green,3CB371,f
580241,15287.0,30385,62.0,1.0,f,62,Chrome Green,3CB371,f
580242,10117.0,4131,351.0,3.0,f,351,Medium Dark Pink,F785B1,f
580243,10117.0,4133,351.0,6.0,f,351,Medium Dark Pink,F785B1,f
580244,10117.0,4728,351.0,3.0,f,351,Medium Dark Pink,F785B1,f
580245,10904.0,4131,351.0,2.0,f,351,Medium Dark Pink,F785B1,f
580246,10904.0,4133,351.0,2.0,f,351,Medium Dark Pink,F785B1,f
580247,10904.0,4728,351.0,4.0,f,351,Medium Dark Pink,F785B1,f
580248,12090.0,6180,1001.0,1.0,f,1001,Medium Violet,9391E4,f
580249,13140.0,3001,1001.0,1.0,f,1001,Medium Violet,9391E4,f
580250,16084.0,51686,1006.0,2.0,f,1006,Trans Light Royal Blue,B4D4F7,t
580251,NaN,NaN,NaN,NaN,NaN,32,Trans-Black IR Lens,635F52,t
580252,NaN,NaN,NaN,NaN,NaN,1004,Trans Flame Yellowish Orange,FCB76D,t
580253,NaN,NaN,NaN,NaN,NaN,1005,Trans Fire Yellow,FBE890,t
580254,NaN,NaN,NaN,NaN,NaN,1007,Reddish Lilac,8E5597,f

In [12]:
inv_set = df_inv.merge(df_sets

,set_num,name,year,theme_id,num_parts
0,00-1,Weetabix Castle,1970,414,471
1,0011-2,Town Mini-Figures,1978,84,12
2,0011-3,Castle 2 for 1 Bonus Offer,1987,199,2
3,0012-1,Space Mini-Figures,1979,143,12
4,0013-1,Space Mini-Figures,1979,143,12
5,0014-1,Space Mini-Figures,1979,143,12
6,0015-1,Space Mini-Figures,1979,143,18
7,0016-1,Castle Mini Figures,1978,186,15
8,00-2,Weetabix Promotional House 1,1976,413,147
9,00-3,Weetabix Promotional House 2,1976,413,149
10,00-4,Weetabix Promotional Windmill,1976,413,126
11,005-1,Basic Building Set in Cardboard,1965,366,35
12,00-6,Special Offer,1985,67,3
13,00-7,Weetabix Promotional Lego Village,1976,413,3
14,010-1,Basic Building Set in Cardboard,1965,366,57
15,010-3,Basic Building Set,1968,366,77
16,011-1,Basic Building Set,1968,366,145
17,022-1,Basic Building Set,1968,366,110
18,03093-1,The Race to Build It Board Game,1999,502,70
19,033-2,Basic Building Set,1968,366,177
20,044-1,Basic Building Set,1968,366,225
21,055-2,Basic Building Set,1968,366,256
22,066-1,Basic Building Set,1968,366,407
23,080-1,Basic Building Set with Train,1967,366,710
24,088-1,Super Set,1969,469,615
25,10000-1,Guarded Inn,2001,186,256
26,10001-1,Metroliner,2001,233,785
27,10002-1,Railroad Club Car,2001,233,272
28,10003-1,1 x 2 Sand Red Bricks,2001,254,100
29,10004-1,2 x 2 Sand Red Bricks,2001,254,100
...,...,...,...,...,...
11643,TRUXWINGTIE-1,"TRU X-Wing Fighter & TIE Fighter (May 3, 2014)",2014,170,2
11644,tsuper-1,Technic Super Set,1991,12,3
11645,Vancouver-1,"LEGO Store Grand Opening Exclusive Set, Oakrid...",2012,408,-1
11646,Victor-1,"LEGO Store Grand Opening Exclusive Set, Eastvi...",2012,408,15
11647,Vienna-1,"LEGO Store Grand Opening Exclusive Set, SCS, W...",2013,408,17
11648,VP-1,Ice Planet Co-Pack of 6814 6879 and 6898,1995,133,3
11649,VP-10,Star Wars Value Pack with Free LEGO Backpack (...,2003,170,4
11650,VP-11,Star Wars Co-Pack of 7101 7111 and 7131,2000,166,3
11651,VP-12,Star Wars Co-Pack of 7121 and 7151,2000,166,2
11652,VP-13,Launch Command Value Pack - (6336 6516 6614),1995,88,3
11653,VP-14,Classic Town Value Pack Duopack (6581 6596),1998,67,2
11654,VP-15,Adventurers Super Value Pack,2000,298,3
11655,VP-17,Legoland Town Special Offer,1985,67,0
11656,VP-2,Star Wars Co-Pack of 7110 and 7144,2001,169,2
11657,VP-3,Star Wars Co-Pack of 7131 and 7151,2000,166,2
11658,VP-4,Star Wars Co-Pack of 7101 7111 and 7171,2000,166,3
11659,VP-5,UFO Value Pack,1997,144,3
11660,VP-6,Building Bonanza Value Pack 4886 with 7280 & 7281,2006,52,3
11661,VP-7,Fire Value Pack (6554 6407 6564),1997,98,3
11662,VP-8,Star Wars Co-Pack of 7130 and 7150,2000,169,2
11663,VPorient-1,Orient Expedition Value Pack with LEGO Backpac...,2003,300,4
11664,vwkit-1,Volkswagen Kit,1959,366,22
11665,W098-1,"Watch Set, Classic Blue",2006,501,0
11666,W991526-1,Homeschool Introduction to Simple and Motorize...,2009,529,0
11667,Watford-1,"LEGO Store Grand Opening Exclusive Set, Watfor...",2013,408,15
11668,Wauwatosa-1,"LEGO Store Grand Opening Exclusive Set, Mayfai...",2012,408,15
11669,WHITEHOUSE-1,Micro White House,2015,598,59
11670,Wiesbaden-1,"LEGO Store Grand Opening Exclusive Set, Wiesba...",2010,408,146
11671,WishingWell-1,Wishing Well [Toys R Us Promo],2013,494,28
11672,wwgp1-1,Wild West Limited Edition Gift Pack,1996,476,3