In [10]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['pdf.fonttype'] =42
import matplotlib.ticker as ticker
import matplotlib.patches as mpatches

In [11]:
df_mus = pd.read_csv("MusicGenrePreference.csv")
df_mus.head()

   user.id                     genre        date                score
0       73  indie / alternative rock  2008-09-22                  NaN
1       55  indie / alternative rock  2008-09-19                  NaN
2       36  indie / alternative rock  2008-09-19  2 Moderate Interest
3       39  indie / alternative rock  2008-09-18                  NaN
4       37  indie / alternative rock  2008-09-16      3 High Interest

In [12]:
df_stress = pd.read_csv("FluSymptoms.csv")
df_stress.head()

,user_id,time,sore.throat.cough,runnynose.congestion.sneezing,fever,nausea.vomiting.diarrhea,sad.depressed,open.stressed
0,2,2009-01-09 19:38:00,0,0,0,0,1,1
1,2,2009-01-10 13:36:00,0,0,0,0,1,1
2,2,2009-01-11 12:58:00,0,0,0,0,0,0
3,2,2009-01-12 09:43:00,0,0,0,1,0,0
4,2,2009-01-13 12:18:00,0,0,0,0,0,0

In [13]:
df_stress.shape

(3878, 8)

In [15]:
df_stress.groupby('user_id')['open.stressed'].value_counts().head()

user_id  open.stressed
2        0                 81
         1                 17
4        0                126
         1                  2
5        0                 52
Name: open.stressed, dtype: int64

In [18]:
df_new1 = df_stress.loc[df_stress['open.stressed'] == 1]
df_new1.head()

,user_id,time,sore.throat.cough,runnynose.congestion.sneezing,fever,nausea.vomiting.diarrhea,sad.depressed,open.stressed
0,2,2009-01-09 19:38:00,0,0,0,0,1,1
1,2,2009-01-10 13:36:00,0,0,0,0,1,1
12,2,2009-01-21 15:16:00,0,0,0,1,1,1
16,2,2009-01-24 12:32:00,0,0,0,1,1,1
28,2,2009-02-04 09:23:00,1,1,0,0,1,1

In [19]:
df1 = df_new1.merge(df_mus, left_on= 'user_id', right_on='user.id')
df1

,user_id,time,sore.throat.cough,runnynose.congestion.sneezing,fever,nausea.vomiting.diarrhea,sad.depressed,open.stressed,user.id,genre,date,score
0,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,indie / alternative rock,2008-09-15,1 Slight Interest
1,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,classic rock,2008-09-15,1 Slight Interest
2,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,heavy metal / hardcore,2008-09-15,3 High Interest
3,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,pop / top 40,2008-09-15,NaN
4,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,techno / lounge / electronic,2008-09-15,NaN
5,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,hip-hop / r&b,2008-09-15,NaN
6,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,jazz,2008-09-15,1 Slight Interest
7,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,classical,2008-09-15,1 Slight Interest
8,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,country / folk,2008-09-15,NaN
9,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,showtunes,2008-09-15,NaN
10,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,other,2008-09-15,NaN
11,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,indie / alternative rock,2008-10-29,2 Moderate Interest
12,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,classic rock,2008-10-29,2 Moderate Interest
13,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,heavy metal / hardcore,2008-10-29,3 High Interest
14,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,pop / top 40,2008-10-29,NaN
15,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,techno / lounge / electronic,2008-10-29,1 Slight Interest
16,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,hip-hop / r&b,2008-10-29,NaN
17,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,jazz,2008-10-29,2 Moderate Interest
18,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,classical,2008-10-29,NaN
19,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,country / folk,2008-10-29,NaN
20,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,showtunes,2008-10-29,1 Slight Interest
21,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,other,2008-10-29,NaN
22,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,indie / alternative rock,2009-05-20,2 Moderate Interest
23,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,classic rock,2009-05-20,NaN
24,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,heavy metal / hardcore,2009-05-20,1 Slight Interest
25,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,pop / top 40,2009-05-20,NaN
26,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,techno / lounge / electronic,2009-05-20,NaN
27,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,hip-hop / r&b,2009-05-20,3 High Interest
28,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,jazz,2009-05-20,NaN
29,2,2009-01-09 19:38:00,0,0,0,0,1,1,2,classical,2009-05-20,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
24973,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,pop / top 40,2009-03-14,NaN
24974,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,techno / lounge / electronic,2009-03-14,1 Slight Interest
24975,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,hip-hop / r&b,2009-03-14,NaN
24976,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,jazz,2009-03-14,3 High Interest
24977,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,classical,2009-03-14,3 High Interest
24978,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,country / folk,2009-03-14,NaN
24979,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,showtunes,2009-03-14,3 High Interest
24980,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,other,2009-03-14,NaN
24981,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,indie / alternative rock,2009-05-20,3 High Interest
24982,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,classic rock,2009-05-20,NaN
24983,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,heavy metal / hardcore,2009-05-20,NaN
24984,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,pop / top 40,2009-05-20,NaN
24985,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,techno / lounge / electronic,2009-05-20,NaN
24986,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,hip-hop / r&b,2009-05-20,NaN
24987,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,jazz,2009-05-20,2 Moderate Interest
24988,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,classical,2009-05-20,NaN
24989,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,country / folk,2009-05-20,NaN
24990,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,showtunes,2009-05-20,NaN
24991,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,other,2009-05-20,NaN
24992,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,indie / alternative rock,2009-06-02,3 High Interest
24993,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,classic rock,2009-06-02,3 High Interest
24994,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,heavy metal / hardcore,2009-06-02,NaN
24995,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,pop / top 40,2009-06-02,1 Slight Interest
24996,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,techno / lounge / electronic,2009-06-02,1 Slight Interest
24997,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,hip-hop / r&b,2009-06-02,1 Slight Interest
24998,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,jazz,2009-06-02,3 High Interest
24999,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,classical,2009-06-02,3 High Interest
25000,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,country / folk,2009-06-02,1 Slight Interest
25001,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,showtunes,2009-06-02,2 Moderate Interest
25002,80,2009-02-22 10:56:00,1,0,0,0,0,1,80,other,2009-06-02,NaN

In [30]:
popular = df1.groupby('user_id')['genre'].value_counts()
popular.groupby(level=0).nlargest(1).head()

user_id  user_id  genre
2        2        classic rock    68
4        4        classic rock     8
5        5        classic rock     8
6        6        classic rock    51
7        7        classic rock     8
Name: genre, dtype: int64

In [21]:
df_new2 = df_stress.loc[df_stress['open.stressed'] == 0]
df_new2.head()

,user_id,time,sore.throat.cough,runnynose.congestion.sneezing,fever,nausea.vomiting.diarrhea,sad.depressed,open.stressed
2,2,2009-01-11 12:58:00,0,0,0,0,0,0
3,2,2009-01-12 09:43:00,0,0,0,1,0,0
4,2,2009-01-13 12:18:00,0,0,0,0,0,0
5,2,2009-01-14 11:16:00,0,0,0,0,1,0
6,2,2009-01-15 17:21:00,0,0,0,0,0,0

In [22]:
df2 = df_new2.merge(df_mus, left_on= 'user_id', right_on='user.id')
df2

,user_id,time,sore.throat.cough,runnynose.congestion.sneezing,fever,nausea.vomiting.diarrhea,sad.depressed,open.stressed,user.id,genre,date,score
0,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,indie / alternative rock,2008-09-15,1 Slight Interest
1,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,classic rock,2008-09-15,1 Slight Interest
2,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,heavy metal / hardcore,2008-09-15,3 High Interest
3,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,pop / top 40,2008-09-15,NaN
4,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,techno / lounge / electronic,2008-09-15,NaN
5,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,hip-hop / r&b,2008-09-15,NaN
6,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,jazz,2008-09-15,1 Slight Interest
7,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,classical,2008-09-15,1 Slight Interest
8,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,country / folk,2008-09-15,NaN
9,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,showtunes,2008-09-15,NaN
10,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,other,2008-09-15,NaN
11,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,indie / alternative rock,2008-10-29,2 Moderate Interest
12,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,classic rock,2008-10-29,2 Moderate Interest
13,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,heavy metal / hardcore,2008-10-29,3 High Interest
14,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,pop / top 40,2008-10-29,NaN
15,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,techno / lounge / electronic,2008-10-29,1 Slight Interest
16,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,hip-hop / r&b,2008-10-29,NaN
17,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,jazz,2008-10-29,2 Moderate Interest
18,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,classical,2008-10-29,NaN
19,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,country / folk,2008-10-29,NaN
20,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,showtunes,2008-10-29,1 Slight Interest
21,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,other,2008-10-29,NaN
22,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,indie / alternative rock,2009-05-20,2 Moderate Interest
23,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,classic rock,2009-05-20,NaN
24,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,heavy metal / hardcore,2009-05-20,1 Slight Interest
25,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,pop / top 40,2009-05-20,NaN
26,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,techno / lounge / electronic,2009-05-20,NaN
27,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,hip-hop / r&b,2009-05-20,3 High Interest
28,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,jazz,2009-05-20,NaN
29,2,2009-01-11 12:58:00,0,0,0,0,0,0,2,classical,2009-05-20,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
127922,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,pop / top 40,2009-03-14,NaN
127923,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,techno / lounge / electronic,2009-03-14,1 Slight Interest
127924,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,hip-hop / r&b,2009-03-14,NaN
127925,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,jazz,2009-03-14,3 High Interest
127926,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,classical,2009-03-14,3 High Interest
127927,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,country / folk,2009-03-14,NaN
127928,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,showtunes,2009-03-14,3 High Interest
127929,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,other,2009-03-14,NaN
127930,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,indie / alternative rock,2009-05-20,3 High Interest
127931,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,classic rock,2009-05-20,NaN
127932,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,heavy metal / hardcore,2009-05-20,NaN
127933,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,pop / top 40,2009-05-20,NaN
127934,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,techno / lounge / electronic,2009-05-20,NaN
127935,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,hip-hop / r&b,2009-05-20,NaN
127936,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,jazz,2009-05-20,2 Moderate Interest
127937,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,classical,2009-05-20,NaN
127938,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,country / folk,2009-05-20,NaN
127939,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,showtunes,2009-05-20,NaN
127940,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,other,2009-05-20,NaN
127941,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,indie / alternative rock,2009-06-02,3 High Interest
127942,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,classic rock,2009-06-02,3 High Interest
127943,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,heavy metal / hardcore,2009-06-02,NaN
127944,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,pop / top 40,2009-06-02,1 Slight Interest
127945,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,techno / lounge / electronic,2009-06-02,1 Slight Interest
127946,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,hip-hop / r&b,2009-06-02,1 Slight Interest
127947,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,jazz,2009-06-02,3 High Interest
127948,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,classical,2009-06-02,3 High Interest
127949,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,country / folk,2009-06-02,1 Slight Interest
127950,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,showtunes,2009-06-02,2 Moderate Interest
127951,80,2009-02-28 11:04:00,0,0,0,0,0,0,80,other,2009-06-02,NaN

In [25]:
popular2 = df2.groupby('user_id')['genre'].value_counts()
popular2.groupby(level=0).nlargest(1)

user_id  user_id  genre
2        2        classic rock    324
4        4        classic rock    504
5        5        classic rock    208
6        6        classic rock      9
7        7        classic rock    364
8        8        classic rock    396
9        9        classic rock     72
11       11       classic rock      8
12       12       classic rock     18
15       15       classic rock    183
18       18       classic rock     54
20       20       classic rock    292
21       21       classic rock    256
22       22       classic rock    240
23       23       classic rock    260
24       24       classic rock    232
26       26       classic rock    124
27       27       classic rock    144
28       28       classic rock     84
29       29       classic rock    108
30       30       classic rock     58
31       31       classic rock    132
32       32       classic rock    146
33       33       classic rock     54
34       34       classic rock     64
35       35       classic rock     44
36       36       classic rock     87
37       37       classic rock    360
38       38       classic rock     22
40       40       classic rock    124
                                 ...
46       46       classic rock    380
47       47       classic rock    172
48       48       classic rock     76
49       49       classic rock     76
51       51       classic rock     36
52       52       classic rock    114
54       54       classic rock    352
55       55       classic rock    112
56       56       classic rock    312
57       57       classic rock    248
58       58       classic rock    416
59       59       classic rock    528
60       60       classic rock    176
61       61       classic rock    384
62       62       classic rock    280
63       63       classic rock    129
64       64       classic rock    160
66       66       classic rock     96
67       67       classic rock    100
68       68       classic rock     68
69       69       classic rock    320
70       70       classic rock    472
71       71       classic rock    172
72       72       classic rock    204
75       75       classic rock    318
76       76       classic rock    108
77       77       classic rock     26
78       78       classic rock     81
79       79       classic rock    186
80       80       classic rock     87
Name: genre, Length: 64, dtype: int64